name: 云效同步

on:
  push:
    branches: master

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Sync
      uses: mengyou1024/codeup-action@v0.0.0
      with:
        accessKeyId: ${{ secrets.CODEUPACCESSKEYID }}
        accessKeySecret: ${{ secrets.CODEUPACCESSKEYSECRET }}
        accessToken: ${{ secrets.CODEUPACCESSTOKEN }}
        organizationId: ${{ vars.CODEUPORGANIZATIONID }}
        repositoryName: ${{ vars.CODEUPREPOSITORYNAME }}
